name: Install ABINIT
run-name: ${{ github.actor }} is installing abinit

on:
  workflow_run:
    workflows: ["Install LibXC"]
    types: 
      - completed

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and compile ABINIT
        run: |
          git clone https://github.com/abinit/abinit.git
          cd abinit
          ./autogen.sh
          ./configure --with-libxc=/home/runner/libxc/lib/
          make
          sudo make install

        continue-on-error: true

      - name: Copy config.log on failure
        if: failure()
        run: |
          ls abinit
          cd ~
          ls abinit
          echo abinit/config.log
          cp abinit/config.log ${{ github.workspace }}

      - name: Copy config.log on success
        run: |
          ls abinit
          cd ~
          ls abinit
          echo abinit/config.log
          cp abinit/config.log ${{ github.workspace }}