name: Install ABINIT

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf libtool pkg-config liblapack-dev libblas-dev libfftw3-dev libnetcdf-dev libnetcdff-dev

    - name: Download and Compile LibXC
      run: |
        wget http://www.tddft.org/programs/libxc/down.php?file=4.3.4/libxc-4.3.4.tar.gz -O libxc-4.3.4.tar.gz
        tar -xvf libxc-4.3.4.tar.gz
        cd libxc-4.3.4
        ./configure --prefix=$HOME/libxc
        make
        make install
        cd ..

    - name: Set environment variables
      run: |
        echo "LIBXC_DIR=$HOME/libxc" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/libxc/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo $GITHUB_ENV
        ls $LIBXC_DIR
        ls $LD_LIBRARY_PATH

    - name: Download and compile ABINIT
      run: |
        git clone https://github.com/abinit/abinit.git
        cd abinit
        ./autogen.sh
        echo 
        ./configure --with-libxc=$LD_LIBRARY_PATH
        make
        sudo make install