name: Install LibXC
run-name: ${{ github.actor }} is installing libxc

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache LibXC
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/libxc
          key: libxc-4.3.4-${{ runner.os }}-${{ hashFiles('**/libxc-4.3.4.tar.gz') }}
          restore-keys: |
            libxc-4.3.4-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf libtool pkg-config liblapack-dev libblas-dev libfftw3-dev libnetcdf-dev libnetcdff-dev

      - name: Download and Compile LibXC
        run: |
          if [ ! -d "$HOME/libxc" ]; then
            wget http://www.tddft.org/programs/libxc/down.php?file=4.3.4/libxc-4.3.4.tar.gz -O libxc-4.3.4.tar.gz
            tar -xvf libxc-4.3.4.tar.gz
            cd libxc-4.3.4
            ./configure --prefix=$HOME/libxc
            make
            make install
          fi
          echo "Listing contents of /home/runner/libxc:"
          ls /home/runner/libxc
          echo "Listing contents of /home/runner/libxc/lib:"
          ls /home/runner/libxc/lib
          cd ..

          du -h $HOME/libxc

      - name: Set environment variables for LibXC
        run: |
          echo "Below steps aren't used..."
          echo "LIBXC_DIR=$HOME/libxc" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/libxc/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          ls /home/runner/libxc
